## WAP TO ACCEPT A CHARACTER FROM THE USER AND DISPLAY WHETHER IT IS A VOWEL OR CONSONANT?
ch = input("Enter any character:- ")
if ch == 'A' or ch == 'a':
    print(f'{ch} is a Vowel')
elif ch == 'E' or ch == 'e':
    print(f'{ch} is a Vowel')
elif ch == 'I' or ch == 'i':
    print(f'{ch} is a Vowel')
elif ch == 'O' or ch == 'o':
    print(f'{ch} is a Vowel')
elif ch == 'U' or ch == 'u':
    print(f'{ch} is a Vowel')
else:
    print(f'{ch} is a Consonant')
