## DEFINING A FUNCTION
## DIVIDED LARGE TASK INTO MANY SMALL TASK, HALPFUL FOR DEBUGING CODE?
## ADDITION USE FUNCTION
def add():
    x = int(input("Enter the first number:- "))
    y = int(input("Enter the second Number:- "))
    z = x + y
    print(z)
add()


## SUBSTRACTION USE FUNCTION
def sub():
    x = int(input("Enter the first number:- "))
    y = int(input("Enter the second Number:- "))
    z2 = x - y
    print(z2)
sub()

## WAP TO PRINT THE FUNCTION WITHOUT ARGUMENT AND PARAMETER?
## WAP TO FIND THE DEFINING FUNCTION WITHOUT PARAMETER?
def w():
    x = 20
    y = 30
    z = x + y
    print(z)
w()

print()
## WAP TO PRINT THE FUNCTION WITH ARGUMENT AND PARAMETER?
## WAP TO FIND THE DEFINING FUNCTION WITH PARAMETER?
def w1(y):
    x = 20
    z = x + y
    print(z)
w1(39)

print()
def f(y):
    x = "I a "
    z = x + y
    print(z)
f('Mampu Roy')