## HOW TO MULTIPLY NUMBERS IN PYTHON USER DEFINE?
## USING FOR LOOP AND WHILE LOOP
num = int(input("Enter Any Number:- "))
temp = num * num
print(temp)

print()
## HOW TO MULTIPLY FLOAT NUMBERS IN PYTHON?
n1 = float(input("Enter any number:- "))
tm = n1 * n1
print(tm)

print()
## HOW TO MULTIPLY COMPLEX NUMBERS IN PYTHON?
n1 = complex(input("Enter any number:- "))
tm = n1 * n1
print(tm)

print()
## HOW TO MULTIPLY STRING WITH AN INTEGER IN PYTHON
def row(s, n):
    return s * n
print(row('hello all\n', 5))

print()
def row():
    s = "hello all\n"
    n = 5
    z = s * n
    print(z)
row()
## 

print()
## HOW TO MULTIPLY TWO NUMBERS USING THE FUNCTION IN PYTHON?
def r1(x, y):
    return x * y
s = r1(7, 7)
print(s)

print()
def r1(x, y):
    return x * y
s = r1(7, 7)
print(s)