## WAP TO FIND THE AREA OF TRIANGLE?
## FORMULA:- AREA OF TRIANGLE:- 
## area = 1/2 * base * height
base = int(input("Enter the number of base:- "))
height = int(input("Enter the number of area:- "))
area = 1/2 * base * height
print("The area of triangle=>", area)

## USE FUNCTION
def show():
    base = int(input("Enter the number of base:- "))
    height = int(input("Enter the number of height:- "))
    area = 1/2 * base * height
    print("The area of triangle:- ", area)
show()