## WAP TO FIND THE AREA OF CIRCLE USING FUNCTION PROGRAM?
def area():
    pi = 22/7
    radius = float(input("Enter radius Circle:- "))
    print(f'Area of circle with {radius} is {pi * radius}')
area()

print()
radius1 = float(input("Enter radius circle:- "))
pi = 22/7
print(f'Area of circle with{radius1} is {pi * radius1}')


print()
## WAP TO PRINT MULTIPLICATION AND ADD THAT NUMBER WITH FUNCTION?
num = int(input("Enter a Number:- "))
sqr = num * num
def add(sqr, num):
    st = sqr + num
    print(st)
add(sqr, num)

print()
def add1():
    num = int(input("Enter a NUmber:- "))
    sqr = num * num
    st = sqr + num
    print(st)
add1()

print()
## WAP TO MULTIPLICATOR AND MULTIPLY THAT NUMBER WITH FUNCTION?
def multiply():
    num = int(input("Enter a Number:- "))
    sqr = num * num
    sqr2 = sqr * num
    print(sqr2)
multiply()

print()
num1 = int(input("Enter a Number:- "))
sqr1 = num * num
def mult2():
    sqr3 = sqr1 * num
    print(sqr3)
mult2()

print()
## WAP TO PRINT MULTIPLICATION AND DEVISION THAT NUMBERS WITH FUNCTION?
n = int(input("Enter a Number:- "))
s1 = (n * n)
def dev():
    s2 = (s1 * n)
    print(s2)
dev()